import { ReactNode } from 'react';
import { MaterialUiProvider } from '../src/providers/material-ui/material-ui.provider';
import { roboto } from '../src/fonts/roboto-font/roboto.font';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <MaterialUiProvider>{children}</MaterialUiProvider>
      </body>
    </html>
  );
}
